/* $Id$
 *
 * Tab Spacing = 4
 *
 * Copyright (c) 2004-2005, The Pangburn Company, Prasanth R. Pasala and
 * Diego Gil
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.  Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials
 * provided with the distribution.  The names of its contributors may not be
 * used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

package com.nqadmin.swingSet.formatting.helpers;
import java.awt.event.ActionListener;

/**
 *
 * @author  dags
 */
public class SelectorPopupPanel extends javax.swing.JPanel implements ActionListener {
    
    private javax.swing.ListModel model = null;
    
    /** Creates new form SelectorPopupPanel */
    public SelectorPopupPanel() {
        initComponents();
        selectorList1.setModel(selectorListModel1);        
    }
    
    public SelectorPopupPanel(javax.swing.ListModel model) {
        initComponents();
        selectorList1.setModel(model);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        sSConnection1 = new com.nqadmin.swingSet.datasources.SSConnection();
        selectorListModel1 = new com.nqadmin.swingSet.formatting.helpers.SelectorListModel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectorList1 = new com.nqadmin.swingSet.formatting.helpers.SelectorList();
        jLabel1 = new javax.swing.JLabel();

        sSConnection1.setDriverName("org.postgresql.Driver");
        sSConnection1.setUrl("jdbc:postgresql://localhost/mag");
        sSConnection1.setUsername("dags");
        try {
            sSConnection1.createConnection();
        }
        catch (java.lang.ClassNotFoundException nf) {
            System.out.println(nf);
        }
        catch (java.lang.Exception ex) {
            System.out.println(ex);
        }
        selectorListModel1.setDataColumn("publication_id");
        selectorListModel1.setListColumn("publication_title");
        selectorListModel1.setOrderBy("publication_title");
        selectorListModel1.setSsConnection(sSConnection1);
        selectorListModel1.setTable("publications");
        selectorListModel1.refresh();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("Selector"));
        setFocusable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.setColumns(20);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.8;
        jPanel1.add(jTextField1, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10));
        jButton1.setText("Buscar");
        jButton1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jButton1, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setFocusable(false);
        selectorList1.setDoubleBuffered(true);
        jScrollPane1.setViewportView(selectorList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecci\u00f3n");
        add(jLabel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JTextField s;
        int j, n;
        // text to find 
        String toFind = null;
        s= ((javax.swing.JTextField)evt.getSource());
        toFind = s.getText().toUpperCase();
        s.setText(toFind);
        System.out.println("Texto a buscar : " + toFind);
        n = selectorList1.getModel().getSize();
        
        /**
         * Here implements list search logic. 
         *
         *
         */
        
        for (j= 0; j < n; j++) {
            String texto = selectorList1.getModel().getElementAt(j).toString().toUpperCase();
            System.out.println("Comparando con " + texto);
            if (texto.startsWith(toFind)) {
                selectorList1.setSelectedIndex(j);
                selectorList1.ensureIndexIsVisible(j);
                selectorList1.requestFocus();
                break;
            }
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void setModel(javax.swing.ListModel model) {
        this.model = model;
        selectorList1.setModel(this.model);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.out.println("Search Action Performed");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField jTextField1;
    com.nqadmin.swingSet.datasources.SSConnection sSConnection1;
    com.nqadmin.swingSet.formatting.helpers.SelectorList selectorList1;
    com.nqadmin.swingSet.formatting.helpers.SelectorListModel selectorListModel1;
    // End of variables declaration//GEN-END:variables
      
    public static void main(String args[])
    {
        // ejemplo
        javax.swing.JFrame frame = new javax.swing.JFrame();
        frame.setLayout(new java.awt.BorderLayout());
        frame.add(new SelectorPopupPanel(), java.awt.BorderLayout.CENTER);
        frame.setSize(640, 480);
        frame.setVisible(true);
    }

    public void actionPerformed(java.awt.event.ActionEvent e) {
    }
}
