/*
 * SelectorTest.java
 *
 * Created on 4 de diciembre de 2004, 12:46
 */

package com.nqadmin.swingSet.formatting.selectors;

/**
 *
 * @author  dags
 */
public class SelectorTest extends javax.swing.JFrame {
    
    /** Creates new form SelectorTest */
    public SelectorTest() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        sSConnection1 = new com.nqadmin.swingSet.datasources.SSConnection();
        helperPopup1 = new com.nqadmin.swingSet.formatting.selectors.HelperPopup();
        helperPopup2 = new com.nqadmin.swingSet.formatting.selectors.HelperPopup();
        helperPopup3 = new com.nqadmin.swingSet.formatting.selectors.HelperPopup();
        jPanel1 = new javax.swing.JPanel();
        sSFormattedTextField1 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();
        sSFormattedTextField2 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();
        sSFormattedTextField3 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();

        sSConnection1.setDriverName("org.postgresql.Driver");
        sSConnection1.setUrl("jdbc:postgresql://localhost/mag");
        sSConnection1.setUsername("dags");
        try {
            sSConnection1.createConnection();
        }
        catch(java.lang.ClassNotFoundException nf){

        }
        catch (java.lang.Exception exe) {

        }
        helperPopup1.setDataColumn("publication_id");
        helperPopup1.setListColumn("publication_title");
        helperPopup1.setOrderBy("publication_title");
        helperPopup1.setTable("publications");
        helperPopup1.setTarget(null);
        helperPopup1.setConnection(sSConnection1);
        helperPopup1.createHelper();

        helperPopup2.setDataColumn("party_id");
        helperPopup2.setListColumn("party_name");
        helperPopup2.setOrderBy("party_name");
        helperPopup2.setTable("parties");
        helperPopup2.setConnection(sSConnection1);
        helperPopup2.createHelper();

        helperPopup3.setConnection(sSConnection1);
        helperPopup3.setDataColumn("account_id");
        helperPopup3.setListColumn("account_name");
        helperPopup3.setOrderBy("account_name");
        helperPopup3.setTable("accounts");
        helperPopup3.createHelper();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SwingSet tests");
        jPanel1.setLayout(new java.awt.BorderLayout());

        sSFormattedTextField1.setColumns(30);
        sSFormattedTextField1.setHelper(helperPopup1);
        sSFormattedTextField1.setValue(new Integer(85));
        jPanel1.add(sSFormattedTextField1, java.awt.BorderLayout.CENTER);

        sSFormattedTextField2.setColumns(30);
        sSFormattedTextField2.setHelper(helperPopup2);
        sSFormattedTextField2.setValue(new Integer(1016));
        jPanel1.add(sSFormattedTextField2, java.awt.BorderLayout.NORTH);

        sSFormattedTextField3.setHelper(helperPopup3);
        sSFormattedTextField3.setValue(new Integer(119));
        jPanel1.add(sSFormattedTextField3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorTest().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    com.nqadmin.swingSet.formatting.selectors.HelperPopup helperPopup1;
    com.nqadmin.swingSet.formatting.selectors.HelperPopup helperPopup2;
    com.nqadmin.swingSet.formatting.selectors.HelperPopup helperPopup3;
    javax.swing.JPanel jPanel1;
    com.nqadmin.swingSet.datasources.SSConnection sSConnection1;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField1;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField2;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField3;
    // End of variables declaration//GEN-END:variables
    
}
