/* $Id$
 *
 * Tab Spacing = 4
 *
 * Copyright (c) 2004, The Pangburn Company, Inc, Prasanth R. Pasala and
 * Diego Gil
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.  Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials
 * provided with the distribution.  The names of its contributors may not be
 * used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

package com.nqadmin.swingSet.formatting.helpers;

/**
 *
 * @author  dags
 */
public class SelectorTest extends javax.swing.JFrame {
    
    /** Creates new form SelectorTest */
    public SelectorTest() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        sSConnection1 = new com.nqadmin.swingSet.datasources.SSConnection();
        helperPopup1 = new com.nqadmin.swingSet.formatting.helpers.HelperPopup();
        helperPopup2 = new com.nqadmin.swingSet.formatting.helpers.HelperPopup();
        helperPopup3 = new com.nqadmin.swingSet.formatting.helpers.HelperPopup();
        jPanel1 = new javax.swing.JPanel();
        sSFormattedTextField1 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();
        sSFormattedTextField2 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();
        sSFormattedTextField3 = new com.nqadmin.swingSet.formatting.SSFormattedTextField();

        sSConnection1.setDriverName("org.postgresql.Driver");
        sSConnection1.setUrl("jdbc:postgresql://localhost/mag");
        sSConnection1.setUsername("dags");
        try {
            sSConnection1.createConnection();
        }
        catch(java.lang.ClassNotFoundException nf){

        }
        catch (java.lang.Exception exe) {

        }
        helperPopup1.setDataColumn("publication_id");
        helperPopup1.setListColumn("publication_title");
        helperPopup1.setOrderBy("publication_title");
        helperPopup1.setTable("publications");
        helperPopup1.setTarget(null);
        helperPopup1.setConnection(sSConnection1);

        helperPopup2.setDataColumn("party_id");
        helperPopup2.setListColumn("party_name");
        helperPopup2.setOrderBy("party_name");
        helperPopup2.setTable("parties");
        helperPopup2.setConnection(sSConnection1);

        helperPopup3.setConnection(sSConnection1);
        helperPopup3.setDataColumn("account_id");
        helperPopup3.setListColumn("account_name");
        helperPopup3.setOrderBy("account_name");
        helperPopup3.setTable("accounts");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SwingSet tests");
        jPanel1.setLayout(new java.awt.BorderLayout());

        sSFormattedTextField1.setColumns(30);
        sSFormattedTextField1.setHelper(helperPopup1);
        sSFormattedTextField1.setValue(new Integer(85));
        jPanel1.add(sSFormattedTextField1, java.awt.BorderLayout.CENTER);

        sSFormattedTextField2.setColumns(30);
        sSFormattedTextField2.setHelper(helperPopup2);
        sSFormattedTextField2.setValue(new Integer(1016));
        jPanel1.add(sSFormattedTextField2, java.awt.BorderLayout.NORTH);

        sSFormattedTextField3.setHelper(helperPopup3);
        sSFormattedTextField3.setValue(new Integer(119));
        jPanel1.add(sSFormattedTextField3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorTest().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    com.nqadmin.swingSet.formatting.helpers.HelperPopup helperPopup1;
    com.nqadmin.swingSet.formatting.helpers.HelperPopup helperPopup2;
    com.nqadmin.swingSet.formatting.helpers.HelperPopup helperPopup3;
    javax.swing.JPanel jPanel1;
    com.nqadmin.swingSet.datasources.SSConnection sSConnection1;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField1;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField2;
    com.nqadmin.swingSet.formatting.SSFormattedTextField sSFormattedTextField3;
    // End of variables declaration//GEN-END:variables
    
}
