#!/bin/bash
#
# $Id$
#
# LINUX JAR CREATION SCRIPT FOR SWINGSET

# DELETE ANY EXISTING RELEASE JARS
rm -r ./release_jars

# MAKE DIRECTORIES NEEDED FOR JARS
mkdir ./release_jars
mkdir ./release_jars/bin
mkdir ./release_jars/docs
mkdir ./release_jars/src
mkdir ./release_jars/src/com
mkdir ./release_jars/src/com/nqadmin
mkdir ./release_jars/src/com/nqadmin/swingSet
mkdir ./release_jars/src/com/nqadmin/swingSet/datasources
mkdir ./release_jars/src/com/nqadmin/swingSet/utils
mkdir ./release_jars/src/com/nqadmin/swingSet/formatting
mkdir ./release_jars/src/com/nqadmin/swingSet/formatting/helpers
mkdir ./release_jars/demo
mkdir ./release_jars/demo/src
mkdir ./release_jars/demo/bin
mkdir ./release_jars/demo/lib
mkdir ./release_jars/images
mkdir ./release_jars/images/icons

# RECOMPILE SWINGSET
javac -source 1.5 -target 1.5 -d ./release_jars/bin -classpath ./lib/glazedlists-1.8.0.jar ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java

# REBUILD JAVADOCS
javadoc -d ./release_jars/docs -classpath ./lib/glazedlists-1.8.0.jar ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java

# COPY SOURCE CODE
cp ./src/com/nqadmin/swingSet/*.java ./release_jars/src/com/nqadmin/swingSet/
rm ./release_jars/src/com/nqadmin/swingSet/*.java~
cp ./src/com/nqadmin/swingSet/datasources/*.java ./release_jars/src/com/nqadmin/swingSet/datasources/
rm ./release_jars/src/com/nqadmin/swingSet/datasources/*.java~
cp ./src/com/nqadmin/swingSet/utils/*.java ./release_jars/src/com/nqadmin/swingSet/utils/
rm ./release_jars/src/com/nqadmin/swingSet/utils/*.java~
cp ./src/com/nqadmin/swingSet/formatting/*.java ./release_jars/src/com/nqadmin/swingSet/formatting/
rm ./release_jars/src/com/nqadmin/swingSet/formatting/*.java~
cp ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./release_jars/src/com/nqadmin/swingSet/formatting/helpers/
rm ./release_jars/src/com/nqadmin/swingSet/formatting/helpers/*.java~

# COPY IMAGES & LICENSE
cp ./src/images/* ./release_jars/images
cp ./src/images/icons/* ./release_jars/images/icons

# BUILD BIN JAR
jar -mcvf ./META-INF/MANIFEST.MF ./release_jars/swingset-bin_current.jar -C ./release_jars/bin com -C ./release_jars images readme.txt ChangeLog.txt FAQ.txt

# BUILD JAVADOC JAR
jar -cvf ./release_jars/swingset-docs_current.jar -C ./release_jars/docs . readme.txt ChangeLog.txt FAQ.txt

# BUILD SOURCE JAR
jar -cvf ./release_jars/swingset-src_current.jar -C ./release_jars/src com -C ./release_jars images readme.txt ChangeLog.txt FAQ.txt

# COMPILE DEMO
javac -source 1.5 -target 1.5 -d ./release_jars/demo/bin -classpath ./lib/glazedlists-1.8.0.jar:./release_jars/swingset-bin_current.jar ./src/samples/Example*.java ./src/samples/MainClass.java

# COPY DEMO SOURCE CODE
cp ./src/samples/*.java ./release_jars/demo/src

# COPY DEMO DEPENDENCIES
cp ./release_jars/swingset-bin_current.jar ./release_jars/demo/lib
cp ./lib/*.jar ./release_jars/demo/lib
cp ./src/samples/suppliers_and_parts.sql ./release_jars/demo
cp ./src/samples/readme.txt ./release_jars/demo

# BUILD DEMO JAR
jar -cvf ./release_jars/swingset-demo_current.jar -C ./release_jars/demo .
