#!/bin/bash
#
# $Id$
#
# LINUX JAR CREATION SCRIPT FOR SWINGSET

# DELETE ANY EXISTING RELEASE JARS
rm -r ./release_jars

# MAKE DIRECTORIES NEEDED FOR JARS
mkdir ./release_jars
mkdir ./release_jars/bin
mkdir ./release_jars/docs
mkdir ./release_jars/src
mkdir ./release_jars/src/com
mkdir ./release_jars/src/com/nqadmin
mkdir ./release_jars/src/com/nqadmin/swingSet
mkdir ./release_jars/src/com/nqadmin/swingSet/datasources
mkdir ./release_jars/demo
mkdir ./release_jars/images
mkdir ./release_jars/images/icons

# RECOMPILE SWINGSET
javac -source 1.5 -target 1.5 -Xlint:deprecation -Xlint:unchecked -d ./release_jars/bin -classpath ./lib/glazedlists-1.8.0.jar ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java

# COPY IMAGES & LICENSE
cp ./src/images/* ./release_jars/images
cp ./src/images/icons/* ./release_jars/images/icons

# BUILD BIN JAR
jar -mcvf ./META-INF/MANIFEST.MF ./release_jars/swingset-bin_current.jar -C ./release_jars/bin com -C ./release_jars images readme.txt ChangeLog.txt FAQ.txt
