#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET
#
rm -r ./bin
mkdir ./bin
javac  -source 1.4 -target 1.4 -Xlint:deprecation -Xlint:unchecked -d ./bin -classpath "./lib/glazedlists-0.9.5.jar:./bin:" ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java
