#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET
#
rm -r ./bin
mkdir ./bin
javac  -source 1.5 -target 1.5 -Xlint:deprecation -Xlint:unchecked -d ./bin -classpath ./lib/glazedlists-1.11.0.jar ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java
