/* *****************************************************************************
 * Copyright (C) 2025, Ernie R Rael. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * ****************************************************************************/
package com.nqadmin.swingset.navigate;

import java.util.Set;

import javax.sql.RowSet;

import com.nqadmin.swingset.datasources.RSC;

import static com.google.common.collect.Sets.immutableEnumSet;
import static com.nqadmin.swingset.utils.SSUtils.sf;

/**
 * An Event object that bundles events generated through  one or more operatrions
 * on a {@link javax.sql.RowSet}.
 * The event can originate from a {@link NavAction}, from an
 * {@link RSC}/SSComponent, or
 * from something else, use {@link #getOperatorKind} to determine the kind;
 * and use {@link #getComponent() } or {@link #getNavAction() } for
 * the specific operator.
 * The property {@link RowSetEventType} indicates which RowSet events are bundled.
 * Use the NavigationModel to get the RowSet.
 */
@SuppressWarnings("serial")
public class NavigationRowSetEvent extends NavigationEvent
{
	/** The type of NaviagionRowSetEvent events */
	public enum RowSetEventType {
		/** See {@link javax.sql.RowSetListener#cursorMoved(javax.sql.RowSetEvent) } */
		CURSOR_MOVED,
		/** See {@link javax.sql.RowSetListener#rowChanged(javax.sql.RowSetEvent)} */
		ROW_CHANGED,
		/** See {@link javax.sql.RowSetListener#rowSetChanged(javax.sql.RowSetEvent)} */
		ROW_SET_CHANGED,
	}

	/** The type of behavior which caused this event. */
	// TODO: originatingComponentType
	public enum OperatorKind {
		/** A navigation action, typically a user button push, generated this event */
		NAV,
		/** An SSComponent's action generated this event, e.g. user input. */
		COMPONENT,
		/** The event originated from outside of SS. */
		UNKNOWN,
	}

	private final RowSet rs;
	private final OperatorKind operatorKind;
	private final Object operator;
	private final Set<RowSetEventType> rowSetEventTypes;

	/**
	 * An Event object generated for a NavAction on a RowSet.
	 * @param source
	 * @param rs
	 * @param operatorKind
	 * @param operator Either a NavAction or RSC/component; may be null
	 * @param rowSetEventTypes
	 */
	NavigationRowSetEvent(NavigationModel source,
								 RowSet rs,
								 OperatorKind operatorKind,
								 Object operator,
								 Set<RowSetEventType> rowSetEventTypes)
	{
		super(source);
		this.rs = rs;
		this.operatorKind = operatorKind;
		this.operator = operator;
		this.rowSetEventTypes = immutableEnumSet(rowSetEventTypes);

		switch (operatorKind) {
		case COMPONENT -> {
			if (!(operator instanceof RSC))
				throw new IllegalArgumentException(sf("%s must have a component"));
		}
		case NAV -> {
			if (!(operator instanceof NavAction))
				throw new IllegalArgumentException(sf("%s must have a component"));
		}
		case null,default -> {}
		}
	}

	/**
	 * Return the RowSet associated with these events.
	 * @return
	 */
	public RowSet getRowSet()
	{
		return rs;
	}

	/**
	 * The events generated by the navigation action.
	 * @return the events generated by the navigation action.
	 */
	public Set<RowSetEventType> getEventTypes()
	{
		return rowSetEventTypes;
	}

	/**
	 * The actions on the rowset that generated the events.
	 * Null if the OperatorKind is not a NavAction.
	 * 
	 * @return the NavAction that generated the events.
	 */
	public NavAction getNavAction()
	{
		if (operatorKind != OperatorKind.NAV)
			return null;
		return (NavAction) operator;
	}

	/**
	 * The {@link RSC} that originated the event.
	 * Null if the OperatorKind is not an SSComponent.
	 * @return the component that originated the events
	 */
	public RSC getComponent()
	{
		if (operatorKind != OperatorKind.COMPONENT)
			return null;
		return (RSC) operator;
	}

	/**
	 * The source of the rowset operatorKind that generated the events.
	 * @return 
	 */
	public OperatorKind getOperatorKind()
	{
		return operatorKind;
	}

	/** {@inheritDoc} */
	@Override
	public String toString()
	{
		return "NavigationRowSetEvent{" + "rs=" + rs
				+ ", operatorKind=" + operatorKind
				+ ", operator=" + operator
				+ ", rowSetEventTypes=" + rowSetEventTypes + '}';
	}
}
