#!/bin/bash
#
# $Id$
#
# LINUX JAR CREATION SCRIPT FOR SWINGSET

# DELETE ANY EXISTING RELEASE JARS
rm -r ./release_jars

# MAKE DIRECTORIES NEEDED FOR JARS
mkdir ./release_jars
mkdir ./release_jars/bin
mkdir ./release_jars/docs
mkdir ./release_jars/src
mkdir ./release_jars/src/com
mkdir ./release_jars/src/com/nqadmin
mkdir ./release_jars/src/com/nqadmin/swingSet
mkdir ./release_jars/src/com/nqadmin/swingSet/datasources
mkdir ./release_jars/demo
mkdir ./release_jars/images
mkdir ./release_jars/images/icons

# RECOMPILE SWINGSET
javac -source 1.4 -target 1.4 -d ./release_jars/bin ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/*.java

# REBUILD JAVADOCS
javadoc -d ./release_jars/docs ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/*.java

# COPY SOURCE CODE
cp ./src/com/nqadmin/swingSet/*.java ./release_jars/src/com/nqadmin/swingSet/
rm ./release_jars/src/com/nqadmin/swingSet/*.java~
cp ./src/com/nqadmin/swingSet/datasources/*.java ./release_jars/src/com/nqadmin/swingSet/datasources/
rm ./release_jars/src/com/nqadmin/swingSet/datasources/*.java~

# COPY IMAGES & LICENSE
cp ./src/images/* ./release_jars/images
cp ./src/images/icons/* ./release_jars/images/icons

# BUILD BIN JAR
jar -mcvf ./META-INF/MANIFEST.MF ./release_jars/swingset-bin_current.jar -C ./release_jars/bin com -C ./release_jars images readme.txt ChangeLog.txt FAQ.txt

# BUILD JAVADOC JAR
jar -cvf ./release_jars/swingset-docs_current.jar -C ./release_jars/docs . readme.txt ChangeLog.txt FAQ.txt

# BUILD SOURCE JAR
jar -cvf ./release_jars/swingset-src_current.jar -C ./release_jars/src com -C ./release_jars images readme.txt ChangeLog.txt FAQ.txt

# COMPILE DEMO
javac -source 1.4 -target 1.4 -d ./release_jars/demo -classpath ./release_jars/swingset-bin_current.jar  ./src/samples/*.java

# COPY DEMO SOURCE CODE
cp ./src/samples/* ./release_jars/demo/
rm ./release_jars/demo/*.java~

# BUILD DEMO JAR
jar -mcvf ./META-INF/MANIFEST-DEMO.MF ./release_jars/swingset-demo_current.jar -C ./release_jars/demo . readme.txt
