#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET
#
rm -r ./bin
mkdir ./bin
javac -d ./bin ./src/com/nqadmin/swingSet/*.java