#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET
#
rm ./com/nqadmin/swingSet/*.class
javac com/nqadmin/swingSet/*.java