#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET
#
rm -r ./bin
mkdir ./bin
javac  -source 1.4 -target 1.4 -Xlint:deprecation -Xlint:unchecked -d ./bin ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/*.java