#!/bin/bash
#
# $Id$
#
# LINUX JAVADOC GENERATION SCRIPT FOR SWINGSET
#
rm -r ./javadoc
mkdir ./javadoc
javadoc -d ./javadoc ./src/com/nqadmin/swingSet/*.java ./src/com/nqadmin/swingSet/datasources/*.java ./src/com/nqadmin/swingSet/formatting/*.java ./src/com/nqadmin/swingSet/formatting/helpers/*.java ./src/com/nqadmin/swingSet/utils/*.java