#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR SWINGSET DEMO
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR SWINGSET DEMO
#
# CLEAN UP
rm ./*.class

# COMPILE DEMO
javac -source 1.5 -target 1.5 -classpath ./swingset-2.0.1.jar ./MainClass.java