
swingset_logger_level = FINE

#
# Simple java.util.logging configuration to merge into existing config.
#
# NOTE: this is not used if java.util.logging is not used.
#
# TODO: This is probably too simple, set up file name
#

java.util.logging.ConsoleHandler.level = FINE
# following leaves room for WARNI,FINER
java.util.logging.SimpleFormatter.format=%1$tk:%1$tM:%1$tS %4$-5.5s %2$s() - %5$s %n

