/* *****************************************************************************
 * Copyright (C) 2025, Ernie R Rael. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * ****************************************************************************/
package com.nqadmin.swingset;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * x
 */
public class ComboBox2Test
{
	
	/** x */
	public ComboBox2Test()
	{
	}
	
	/** x */
	@BeforeAll
	public static void setUpClass()
	{
	}
	
	/** x */
	@AfterAll
	public static void tearDownClass()
	{
	}
	
	/** x */
	@BeforeEach
	public void setUp()
	{
	}
	
	/** x */
	@AfterEach
	public void tearDown()
	{
	}

	/** x */
	@SuppressWarnings("serial")
	public class ComboBoxIntStringLong extends ComboBox2<Integer, String, Long> { }

	/** x
	 * @param <X>
	 * @param <Y> */
	@SuppressWarnings("serial")
	public class ComboBoxSub<X,Y> extends ComboBox<X, Y> { }

	/** x
	 * @param <X>
	 * @param <Y>
	 * @param <Z> */
	@SuppressWarnings("serial")
	public class ComboBox2Sub<X,Y,Z> extends ComboBox2<X, Y,Z> { }

	/**
	 * Test of setOptions method, of class SSBaseComboBox.
	 * Try 3 mapping types: Integer,Long,String.
	 * For each do regular and autogenerated mapkey.
	 */
	@Test
	@SuppressWarnings("ThrowableResultIgnored")
	public void testCheckTypes()
	{
		System.out.println("CheckTypes");
		ComboBoxIntStringLong cb = new ComboBoxIntStringLong();
		assertEquals(Integer.class, cb.getMappingType());
		assertEquals(String.class, cb.getOptionType());
		assertEquals(Long.class, cb.getOption2Type());

		// "Non generic subclass required, like '%s<...>(){}'"
		assertThrows(IllegalStateException.class, ()->new ComboBoxSub<>());
		assertThrows(IllegalStateException.class, ()->new ComboBox2Sub<>());
		new ComboBox2Sub<>(){};
	}

	/**
	 * Test of setOptions method, of class SSBaseComboBox.
	 * Try 3 mapping types: Integer,Long,String.
	 * For each do regular and autogenerated mapkey.
	 */
	@Test
	@SuppressWarnings("ThrowableResultIgnored")
	public void testSetOptions_List_List()
	{
		System.out.println("setOptions");

		// Long
		ComboBox<Long,String> cbl = new ComboBox<>(){};
		cbl.setOptions(List.of("one", "two"), List.of(11L, 12L));
		cbl.setAllowNull(false);
		List<String> lsl = cbl.getOptions();
		List<Long> lml = cbl.getMappings();
		assertEquals(List.of("one", "two"), lsl);
		assertEquals(List.of(11L, 12L), lml);
		assertFalse(cbl.isAutoGeneratedMapping());

		cbl.setOptions(List.of("onex", "twox"));
		lsl = cbl.getOptions();
		lml = cbl.getMappings();
		assertEquals(List.of("onex", "twox"), lsl);
		assertEquals(List.of(0L, 1L), lml);
		assertTrue(cbl.isAutoGeneratedMapping());
		cbl = null;
		Objects.isNull(cbl);


		// Integer
		ComboBox<Integer,String> cbi = new ComboBox<>(){};
		cbi.setOptions(List.of("one", "two"), List.of(11, 12));
		cbi.setAllowNull(false);
		List<String> lsi = cbi.getOptions();
		List<Integer> lmi = cbi.getMappings();
		assertEquals(List.of("one", "two"), lsi);
		assertEquals(List.of(11, 12), lmi);
		assertFalse(cbi.isAutoGeneratedMapping());

		cbi.setOptions(List.of("onex", "twox"));
		lsi = cbi.getOptions();
		lmi = cbi.getMappings();
		assertEquals(List.of("onex", "twox"), lsi);
		assertEquals(List.of(0, 1), lmi);
		assertTrue(cbi.isAutoGeneratedMapping());
		cbi = null;
		Objects.isNull(cbi);


		// String
		ComboBox<String,String> cbs = new ComboBox<>(){};
		cbs.setOptions(List.of("one", "two"), List.of("11", "12"));
		cbs.setAllowNull(false);
		List<String> lss = cbs.getOptions();
		List<String> lms = cbs.getMappings();
		assertEquals(List.of("one", "two"), lss);
		assertEquals(List.of("11", "12"), lms);
		assertFalse(cbs.isAutoGeneratedMapping());

		{
			ComboBox<String,String> cbsFinal = cbs;
			assertThrows(IllegalArgumentException.class,
					() -> cbsFinal.setOptions(List.of("onex", "twox")));
		}
		cbs = null;
		Objects.isNull(cbs);
	}

	/**
	 * Test of adjustForNullItem method, of class SSBaseComboBox.
	 * 
	 * Also try setSelectedOption()/setSelectedMapping(),
	 * getSelectedMapping()/getSelectedOption()
	 */
	@Test
	public void testAdjustForNullItem()
	{
		System.out.println("adjustForNullItem");

		ComboBox<Long,String> cbl = new ComboBox<>(){};
		cbl.setOptions(List.of("one", "two"), List.of(11L, 12L));
		cbl.setAllowNull(false);
		List<String> lsl = cbl.getOptions();
		List<Long> lml = cbl.getMappings();
		assertEquals(List.of("one", "two"), lsl);
		assertEquals(List.of(11L, 12L), lml);
		assertFalse(cbl.isAutoGeneratedMapping());

		// turn on allow null, this changes what's in the combobox
		cbl.setAllowNull(true);

		lsl = cbl.getOptions();
		lml = cbl.getMappings();
		assertEquals(List.of("", "one", "two"), lsl);
		// Need a list that starts with a null.
		List<Long> ll01 = new ArrayList<>(List.of(11L, 12L));
		ll01.add(0, null);
		assertEquals(ll01, lml);

		cbl = null;
		Objects.isNull(cbl);


		ComboBox<Integer,String> cbi = new ComboBox<>(){};
		cbi.setAllowNull(true);

		// autogenerated
		cbi.setOptions(List.of("onex", "twox"));
		List<String>lsi = cbi.getOptions();
		List<Integer>lmi = cbi.getMappings();
		assertEquals(List.of("", "onex", "twox"), lsi);
		List<Integer> li01 = new ArrayList<>(List.of(0, 1));
		li01.add(0, null);
		assertEquals(li01, lmi);
		assertTrue(cbi.isAutoGeneratedMapping());

		cbi.setSelectedOption("twox");
		assertEquals(1, cbi.getSelectedMapping());
		assertEquals("twox", cbi.getSelectedOption());

		cbi.setSelectedMapping(0);
		assertEquals(0, cbi.getSelectedMapping());
		assertEquals("onex", cbi.getSelectedOption());

		cbi = null;
		Objects.isNull(cbi);
	}

	/**
	 * Test of Enum options
	 */
	@Test
	@SuppressWarnings("ThrowableResultIgnored")
	public void testEnumOption()
	{
		System.out.println("EnumOption");

		enum E {ZERO, ONE, TWO}

		ComboBox<Integer,String> cbi = new ComboBox<>(){};
		cbi.setAllowNull(false);
		cbi.setOptions(E.class);
		cbi.setSelectedEnum(E.ONE);
		assertEquals(E.ONE, cbi.getSelectedEnum());
		assertEquals(E.class, cbi.getEnumOption());
		assertEquals(1, cbi.getSelectedMapping());
		assertEquals("ONE", cbi.getSelectedOption());

		// Only integer key for enum.
		ComboBox<String,String> cbs = new ComboBox<>(){};
		assertThrows(IllegalArgumentException.class,
				() -> cbs.setOptions(E.class));

		// Only String option for enum.
		ComboBox<Integer,Integer> cbii = new ComboBox<>(){};
		assertThrows(IllegalArgumentException.class,
				() -> cbii.setOptions(E.class));
	}

	/**
	 * Test of removeMapping
	 * Also, addOption
	 */
	@Test
	@SuppressWarnings("ThrowableResultIgnored")
	public void testRemoveMapping()
	{
		System.out.println("RemoveMapping");

		ComboBox<Integer,String> cbi = new ComboBox<>(){};
		cbi.setOptions(List.of("one", "two", "three"), List.of(11, 12, 13));
		cbi.setAllowNull(false);
		List<String> lsi = cbi.getOptions();
		List<Integer> lmi = cbi.getMappings();
		assertEquals(List.of("one", "two", "three"), lsi);
		assertEquals(List.of(11, 12, 13), lmi);
		cbi.removeMapping(12);
		lsi = cbi.getOptions();
		lmi = cbi.getMappings();
		assertEquals(List.of("one", "three"), lsi);
		assertEquals(List.of(11, 13), lmi);

		cbi.addOption("four", 14);
		lsi = cbi.getOptions();
		lmi = cbi.getMappings();
		assertEquals(List.of("one", "three", "four"), lsi);
		assertEquals(List.of(11, 13, 14), lmi);
	}
}
